#!/bin/bash

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as root!"$CE"" 1>&2
   sleep 1
   exit
fi

printf '\033]2;activate hhtools\a'

ACTKEY="$( curl "https://pastebin.com/raw/k8D7RBtC" 2>/dev/null )"
sleep 3
echo -e "Enter your hhtools activation key!"
echo -e "You can buy it on the hhtools site!"
read -e -p $'(\033[4;93mactivation_key\033[0m\en)> ' KEYACT
sleep 1
if [[ "$KEYACT" != "$ACTKEY" ]]
then
sleep 1
echo -e "["$RS"*"$CE"] "$RS"Failed to activate hhtools, try again later!"$CE""
sleep 8
exit
fi

r=$(( RANDOM%7999+1001));
s=$(( RANDOM%7999+1001)); 
h=$(( RANDOM% 7999+1001)); 
g=$(( RANDOM% 7999+1001)); 

{
chattr -i /etc/hhtools/root/service
chattr -i /etc/hhtools/root/service/late
chattr -i /etc/hhtools/root/service/hhtkey.txt
chattr -i /etc/hhtools/root/service/late/hhtkey.txt
rm -rf /etc/hhtools
} &> /dev/null

mkdir /etc/hhtools
mkdir /etc/hhtools/root
mkdir /etc/hhtools/root/service
mkdir /etc/hhtools/root/service/late
echo "$r-$s-$h-$g" >> /etc/hhtools/root/service/late/hhtkey.txt
{
chattr -i /dev/config
chattr -i /dev/config/config.txt
chattr -i /dev/config/configure.txt
} &> /dev/null
rm /dev/config/config.txt
rm /dev/config/configure.txt
cat /etc/hhtools/root/service/late/hhtkey.txt >> /dev/config/configure.txt
cat /etc/hhtools/root/service/late/hhtkey.txt >> /dev/config/config.txt
{
chattr +i /dev/config
chattr +i /dev/config/config.txt
chattr +i /dev/config/configure.txt
} &> /dev/null
echo "$ACTKEY" >> /etc/hhtools/root/service/hhtkey.txt
sleep 3

{
chattr +i /etc/hhtools/root/service
chattr +i /etc/hhtools/root/service/late
chattr +i /etc/hhtools/root/service/hhtkey.txt
chattr +i /etc/hhtools/root/service/late/hhtkey.txt
} &> /dev/null
